#!/usr/bin/env bash
# Create draft PR from session state
#
# This script creates a draft pull request with:
# - Original user prompt as description
# - Aggregated commit messages
# - Agent contribution summary

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STATE_DIR="${FORK_JOIN_STATE_DIR:-.fork-join}"

# Arguments
SESSION_ID="${1:-}"

main() {
	if [[ -z "$SESSION_ID" ]]; then
		# Try to get current session
		if [[ -f "${STATE_DIR}/current_session" ]]; then
			SESSION_ID="$(cat "${STATE_DIR}/current_session")"
		else
			echo "Usage: $0 <session-id>" >&2
			exit 1
		fi
	fi

	local session_file="${STATE_DIR}/${SESSION_ID}.json"
	if [[ ! -f "$session_file" ]]; then
		echo "Session file not found: $session_file" >&2
		exit 1
	fi

	# Extract session data
	local feature_branch base_branch original_prompt
	feature_branch="$(jq -r '.feature_branch' "$session_file")"
	base_branch="$(jq -r '.base_branch' "$session_file")"
	original_prompt="$(jq -r '.original_prompt' "$session_file")"

	# Get agent commits
	local agents_json
	agents_json="$(jq -r '.agents | map(select(.commit_message != null))' "$session_file")"

	# Generate PR title from prompt
	local pr_title
	pr_title="$(echo "$original_prompt" | head -c 72 | sed 's/[[:space:]]*$//')"
	if [[ ${#original_prompt} -gt 72 ]]; then
		pr_title="${pr_title}..."
	fi

	# Generate PR body
	local pr_body
	pr_body="$(
		cat <<EOF
## Summary

${original_prompt}

## Agent Contributions

$(echo "$agents_json" | jq -r '.[] | "- **\(.agent_id)** (\(.agent_type // "worker")): \(.commit_message)"')

## Changes

$(git log "${base_branch}..${feature_branch}" --oneline 2>/dev/null || echo "Unable to generate changelog")

---

*This PR was generated by Agent Fork-Join with contributions from $(echo "$agents_json" | jq -r 'length') agent(s).*
EOF
	)"

	# Push branch if needed
	if ! git ls-remote --heads origin "$feature_branch" | grep -q "$feature_branch"; then
		echo "Pushing branch to remote..."
		git push -u origin "$feature_branch"
	fi

	# Create PR using gh CLI
	local pr_url
	pr_url="$(gh pr create \
		--base "$base_branch" \
		--head "$feature_branch" \
		--title "$pr_title" \
		--body "$pr_body" \
		--draft \
		--label "ai-generated" \
		2>&1)"

	local pr_number
	pr_number="$(echo "$pr_url" | grep -oE '[0-9]+$' || echo "")"

	# Update session state with PR number
	if [[ -n "$pr_number" ]]; then
		jq --arg num "$pr_number" --arg url "$pr_url" \
			'.pr_number = ($num | tonumber) | .pr_url = $url | .state = "PR_CREATED"' \
			"$session_file" >"${session_file}.tmp" && mv "${session_file}.tmp" "$session_file"
	fi

	# Output result
	cat <<EOF
{
    "pr_created": true,
    "pr_number": ${pr_number:-null},
    "pr_url": "${pr_url}",
    "feature_branch": "${feature_branch}",
    "base_branch": "${base_branch}"
}
EOF
}

main "$@"
